name: schttp
description: A simple HTTP client supporting a cache.
version: 0.2.6
homepage: https://github.com/Ampless/schttp

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: any
  pedantic: any
