name: schttp
description: A simple HTTP client supporting a cache.
version: 5.0.0-alpha.1
homepage: https://github.com/Ampless/schttp

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  universal_io: ^2.0.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
