name: schttp
description: A simple HTTP client supporting a cache.
version: 5.0.0
homepage: https://github.com/Ampless/schttp

environment:
  sdk: ^3.0.0

dependencies:
  bom: ^1.0.0
  meta: ^1.8.0
  universal_io: ^2.0.4

dev_dependencies:
  lints: ^2.0.0
  tested: ^1.0.0
