name: schttp
description: A simple HTTP client supporting a cache.
version: 4.0.0-alpha.3
homepage: https://github.com/Ampless/schttp

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  universal_io: ^2.0.4

dev_dependencies:
  test: ^1.17.10
  pedantic: ^1.11.1
