name: schttp
description: A simple HTTP client supporting a cache.
version: 3.0.0-alpha.1
homepage: https://github.com/Ampless/schttp

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
