name: schttp
description: A simple HTTP client supporting a cache.
version: 5.0.0-alpha.3
homepage: https://github.com/Ampless/schttp

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bom: ^1.0.0
  universal_io: ^2.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
